[CMD.EXE]
@echo off
lmc.exe=pineskeyoff\@keyoff=champ-wirenkildar,@echo off, mkey=cmd.exe
shutdown:shutdown?/r/m/windows/$pino/shet migrender/span/letench/mik=Aupa h:@echo ellow^^curtcircuit=TX,A-saf=power\par=danger,virus-usalt;Acont;shutdown%domain%impar~$expire<<atall=maker_hospeder&micro{sys.winservidor=pointer,fairkey/toque=rich/Aut=tar=senter_it_sevice/close:rast.imfont;;;KP}
PAG:RASTREND
ARKING:save= H:\SHUTDOWN/S /D \H:\tornatement="[$pino]system=sys/reboot/pause=port/H:D/en=[$pino]
BOOT=command
macre=PRONTCOMMAND
CIFRA:NEXT="TARJETA\REPOSITORY="SHEARP\PRONTCOMMAND="COMMAND:\WINDOWS_SHUTDOWN=WIN=COMPUTER"LAPENGER="GUIPER="EXTENSAO -I -IT = NP = H:WHONGUETS=PAUSE\START="COPYNG\TARJETA=REC\CONTAIN="MYCARD\WINDOWS="C:\CONTAIN\WINDY=FILES\CONNECTION\HOST\IP\PORT\DOWNLOAD\AUT=TECHAREFILE\STINF=SCAN\FOLDER=STINF_SCAN
shourtcut=COMMAND
POSITION=EA icon.PNG
start="interres\redech\coint\keep\command\spotfile\port\files\default=open\C:\macre\block\shourtcut\tarjeta\disk"=g:\macre\diskpart=stinker\default\alpa=files
PAR0=CONTAGER
CONFIG=LOADING
COMMAND=SHUTDOWN S/N /H:D = CONTAGER/COUTER="DNA_speed"
OPEN="CONTAGER"
I:\macre\boot~r=vepidcrek\lmc.exe=I:\BOOT;I:\diskpart=ping\puch=ping\default=dedping\alpa=files\boot2:\boot
filter=macre
BOOT:\EXIT=FACIO
auto=SCAN
????-AFITTER:!=vital
scan=FL-ei&?AIR_scan=start>>?."target.msi"
clock:speed=[00:10:01] scan="aut="time="target.msi\target=leeptime=[contager,>restime<\00:10:00]=p\time=[0]
START=PAUSE